CREATE TABLE mp_user (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  open_id VARCHAR(64) NOT NULL,
  union_id VARCHAR(64) DEFAULT NULL,
  nickname VARCHAR(64) DEFAULT NULL,
  avatar_url VARCHAR(255) DEFAULT NULL,
  mobile VARCHAR(20) DEFAULT NULL,
  role_code VARCHAR(32) NOT NULL DEFAULT 'viewer',
  status TINYINT NOT NULL DEFAULT 1,
  last_login_at DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_open_id (open_id),
  KEY idx_role_code (role_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE origin_region (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  origin_code VARCHAR(32) NOT NULL,
  display_name VARCHAR(64) NOT NULL,
  province VARCHAR(32) NOT NULL,
  city VARCHAR(32) NOT NULL,
  county VARCHAR(32) NOT NULL,
  description VARCHAR(255) DEFAULT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_origin_code (origin_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE orchard (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  origin_id BIGINT UNSIGNED NOT NULL,
  orchard_code VARCHAR(32) NOT NULL,
  orchard_name VARCHAR(64) NOT NULL,
  owner_name VARCHAR(64) DEFAULT NULL,
  contact_phone VARCHAR(20) DEFAULT NULL,
  latitude DECIMAL(10,6) DEFAULT NULL,
  longitude DECIMAL(10,6) DEFAULT NULL,
  altitude DECIMAL(8,2) DEFAULT NULL,
  remark VARCHAR(255) DEFAULT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_orchard_code (orchard_code),
  KEY idx_origin_id (origin_id),
  CONSTRAINT fk_orchard_origin FOREIGN KEY (origin_id) REFERENCES origin_region (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE sample_batch (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  batch_no VARCHAR(40) NOT NULL,
  orchard_id BIGINT UNSIGNED NOT NULL,
  sample_type VARCHAR(32) NOT NULL,
  collected_by VARCHAR(64) DEFAULT NULL,
  collected_at DATETIME NOT NULL,
  sample_count INT NOT NULL DEFAULT 0,
  upload_source VARCHAR(32) DEFAULT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_batch_no (batch_no),
  KEY idx_orchard_id (orchard_id),
  CONSTRAINT fk_sample_batch_orchard FOREIGN KEY (orchard_id) REFERENCES orchard (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE sample_record (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  batch_id BIGINT UNSIGNED DEFAULT NULL,
  sample_code VARCHAR(40) NOT NULL,
  external_code VARCHAR(40) DEFAULT NULL,
  origin_id BIGINT UNSIGNED DEFAULT NULL,
  orchard_id BIGINT UNSIGNED DEFAULT NULL,
  fruit_no VARCHAR(40) DEFAULT NULL,
  current_status VARCHAR(32) NOT NULL DEFAULT 'new',
  quality_grade VARCHAR(16) DEFAULT NULL,
  collected_at DATETIME NOT NULL,
  ssc DECIMAL(8,2) DEFAULT NULL,
  ta DECIMAL(8,3) DEFAULT NULL,
  sugar_acid_ratio DECIMAL(8,2) DEFAULT NULL,
  vc DECIMAL(8,2) DEFAULT NULL,
  pca_x DECIMAL(10,4) DEFAULT NULL,
  pca_y DECIMAL(10,4) DEFAULT NULL,
  is_abnormal TINYINT NOT NULL DEFAULT 0,
  extra_metrics JSON DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_sample_code (sample_code),
  KEY idx_batch_id (batch_id),
  KEY idx_origin_id (origin_id),
  KEY idx_orchard_id (orchard_id),
  KEY idx_current_status (current_status),
  KEY idx_collected_at (collected_at),
  CONSTRAINT fk_sample_record_batch FOREIGN KEY (batch_id) REFERENCES sample_batch (id),
  CONSTRAINT fk_sample_record_origin FOREIGN KEY (origin_id) REFERENCES origin_region (id),
  CONSTRAINT fk_sample_record_orchard FOREIGN KEY (orchard_id) REFERENCES orchard (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE spectral_file (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  sample_id BIGINT UNSIGNED NOT NULL,
  file_name VARCHAR(128) NOT NULL,
  file_type VARCHAR(32) NOT NULL,
  storage_key VARCHAR(255) NOT NULL,
  storage_url VARCHAR(255) DEFAULT NULL,
  wavelength_start DECIMAL(8,2) DEFAULT NULL,
  wavelength_end DECIMAL(8,2) DEFAULT NULL,
  band_count INT DEFAULT NULL,
  file_size BIGINT DEFAULT NULL,
  checksum VARCHAR(64) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_sample_id (sample_id),
  KEY idx_storage_key (storage_key),
  CONSTRAINT fk_spectral_file_sample FOREIGN KEY (sample_id) REFERENCES sample_record (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE model_version (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  model_code VARCHAR(32) NOT NULL,
  model_name VARCHAR(64) NOT NULL,
  model_type VARCHAR(32) NOT NULL,
  version_name VARCHAR(32) NOT NULL,
  framework VARCHAR(32) DEFAULT NULL,
  metrics_json JSON DEFAULT NULL,
  is_active TINYINT NOT NULL DEFAULT 1,
  released_at DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_model_version (model_code, version_name),
  KEY idx_is_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE analysis_task (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  task_no VARCHAR(40) NOT NULL,
  task_type VARCHAR(32) NOT NULL,
  requested_by BIGINT UNSIGNED DEFAULT NULL,
  sample_id BIGINT UNSIGNED NOT NULL,
  compare_sample_id BIGINT UNSIGNED DEFAULT NULL,
  model_version_id BIGINT UNSIGNED DEFAULT NULL,
  input_source VARCHAR(32) DEFAULT NULL,
  task_status VARCHAR(32) NOT NULL DEFAULT 'pending',
  progress INT NOT NULL DEFAULT 0,
  error_message VARCHAR(255) DEFAULT NULL,
  started_at DATETIME DEFAULT NULL,
  finished_at DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_task_no (task_no),
  KEY idx_requested_by (requested_by),
  KEY idx_sample_id (sample_id),
  KEY idx_task_status (task_status),
  KEY idx_created_at (created_at),
  CONSTRAINT fk_analysis_task_user FOREIGN KEY (requested_by) REFERENCES mp_user (id),
  CONSTRAINT fk_analysis_task_sample FOREIGN KEY (sample_id) REFERENCES sample_record (id),
  CONSTRAINT fk_analysis_task_compare_sample FOREIGN KEY (compare_sample_id) REFERENCES sample_record (id),
  CONSTRAINT fk_analysis_task_model_version FOREIGN KEY (model_version_id) REFERENCES model_version (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE analysis_result (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  task_id BIGINT UNSIGNED NOT NULL,
  sample_id BIGINT UNSIGNED NOT NULL,
  predicted_origin_id BIGINT UNSIGNED DEFAULT NULL,
  predicted_origin_name VARCHAR(64) DEFAULT NULL,
  confidence DECIMAL(6,4) DEFAULT NULL,
  predicted_ssc DECIMAL(8,2) DEFAULT NULL,
  predicted_ta DECIMAL(8,3) DEFAULT NULL,
  predicted_ratio DECIMAL(8,2) DEFAULT NULL,
  predicted_vc DECIMAL(8,2) DEFAULT NULL,
  ai_summary TEXT,
  raw_result_json JSON DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_task_id (task_id),
  KEY idx_sample_id (sample_id),
  KEY idx_predicted_origin_id (predicted_origin_id),
  CONSTRAINT fk_analysis_result_task FOREIGN KEY (task_id) REFERENCES analysis_task (id),
  CONSTRAINT fk_analysis_result_sample FOREIGN KEY (sample_id) REFERENCES sample_record (id),
  CONSTRAINT fk_analysis_result_origin FOREIGN KEY (predicted_origin_id) REFERENCES origin_region (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE report_file (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  task_id BIGINT UNSIGNED DEFAULT NULL,
  sample_id BIGINT UNSIGNED DEFAULT NULL,
  report_type VARCHAR(32) NOT NULL,
  file_name VARCHAR(128) NOT NULL,
  storage_key VARCHAR(255) NOT NULL,
  storage_url VARCHAR(255) DEFAULT NULL,
  generated_by BIGINT UNSIGNED DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_task_id (task_id),
  KEY idx_sample_id (sample_id),
  KEY idx_generated_by (generated_by),
  CONSTRAINT fk_report_file_task FOREIGN KEY (task_id) REFERENCES analysis_task (id),
  CONSTRAINT fk_report_file_sample FOREIGN KEY (sample_id) REFERENCES sample_record (id),
  CONSTRAINT fk_report_file_user FOREIGN KEY (generated_by) REFERENCES mp_user (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE operation_log (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED DEFAULT NULL,
  action_type VARCHAR(64) NOT NULL,
  target_type VARCHAR(64) DEFAULT NULL,
  target_id BIGINT UNSIGNED DEFAULT NULL,
  request_id VARCHAR(64) DEFAULT NULL,
  ip_address VARCHAR(64) DEFAULT NULL,
  user_agent VARCHAR(255) DEFAULT NULL,
  remark VARCHAR(255) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_user_id (user_id),
  KEY idx_action_type (action_type),
  KEY idx_target_type_target_id (target_type, target_id),
  KEY idx_created_at (created_at),
  CONSTRAINT fk_operation_log_user FOREIGN KEY (user_id) REFERENCES mp_user (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
